name: hmaidat-sales-stack

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_USERNAME: sales_order
      DB_PASSWORD: 123456
      DB_NAME: sales_orders_db
      DB_HOST: db
      DB_DIALECT: postgres
      EXTERNAL_API_URL: https://eoqef8de0zxqnpm.m.pipedream.net
    ports:
      - "3000:3000"
#    For development with docker
#    volumes:
#      - ./backend:/app
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_USERNAME: sales_order
      DB_PASSWORD: 123456
      DB_NAME: sales_orders_db
      DB_HOST: db
      DB_DIALECT: postgres
      EXTERNAL_API_URL: https://eoqef8de0zxqnpm.m.pipedream.net
#    For development with docker
#    volumes:
#      - ./backend:/app
    depends_on:
      - db
      - redis
    command: npm run worker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sales_order
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sales_orders_db_dev

networks:
  default: { }
